services:
  postgres-service:
    container_name: postgres-service
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: todo-db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
  adminer:
    container_name: adminer
    image: adminer
    restart: unless-stopped
    ports:
      - 9000:8080