server:
  port: 9192

spring:
  r2dbc:
    url: r2dbc:postgresql://${PG_HOST:localhost}:5432/documentation
    username: root
    password: root

  springdoc:
    api-docs:
      enabled: true
    swagger-ui:
      path: /swagger-ui.html

  
  
  
  
  
  security:
    user:
      name: user
      password: password















