
server:
  port: 9192

spring:
  datasource:
    username: postgres
    password: Rh@13801018
    url: jdbc:postgresql://localhost:5432/arousha
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      format_sql: true

  security:
    user:
      name: user
      password: password















