
server:
  port: 9192

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/todo-db
    username: root
    password: root

  spring doc:
    swagger-ui:
      path: /api
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
      format_sql: true

  security:
    user:
      name: user
      password: password















